"""Copy the commute and scores tables to CSV before a migration overwrites them.

    venv/bin/python ops/snapshot_tables.py

The commute rebuild overwrites `medtronic_minutes` and `denver_minutes` in
place, on purpose -- the viewer reads those columns and renaming them would
be a change in two repos. In-place means there is exactly one moment when the
old numbers still exist, and it is before the first traffic-aware run. After
that no query can answer "how far did the ranking move", because the input it
moved from is gone.

So this runs first. It is the whole "before" side of that comparison.

**Read-only.** It opens the connection with `connect()` rather than
`stage_connection()`, so it cannot run `ensure_schema` and cannot alter a
table on the way past, and it issues nothing but SELECTs.

Writes to `data/snapshots/<date>/`, which is gitignored -- these are working
files for one comparison, not history worth committing.
"""

import csv
import shutil
import sys
from datetime import date
from pathlib import Path

# Run as `python ops/<name>.py`, which puts ops/ on sys.path rather than the
# repo root. Same line as ops/canary.py, for the same reason.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.turso_db import connect

TABLES = ("commute", "scores")
SNAPSHOT_ROOT = Path("data") / "snapshots"
RANKED_REPORT = Path("data") / "ranked_report.csv"


def dump_table(conn, table: str, destination: Path) -> int:
    """Write one table to CSV. Returns the row count.

    The column list comes from the rows themselves rather than from `_SCHEMA`,
    so a snapshot taken after a column is added still captures it -- the point
    of the file is to preserve whatever was actually there.
    """
    rows = conn.execute(f"SELECT * FROM {table}").fetchall()
    if not rows:
        destination.write_text("")
        return 0
    columns = list(rows[0].keys())
    with destination.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row[column] for column in columns})
    return len(rows)


def main() -> int:
    out_dir = SNAPSHOT_ROOT / date.today().isoformat()
    out_dir.mkdir(parents=True, exist_ok=True)

    conn = connect()
    for table in TABLES:
        destination = out_dir / f"{table}.csv"
        count = dump_table(conn, table, destination)
        print(f"{table}: {count} rows -> {destination}")

    if RANKED_REPORT.exists():
        shutil.copy2(RANKED_REPORT, out_dir / RANKED_REPORT.name)
        print(f"{RANKED_REPORT.name}: copied -> {out_dir / RANKED_REPORT.name}")
    else:
        # Not fatal: the CSVs above are what the comparison needs. The report
        # is a convenience, and it is regenerated by every scoring run.
        print(f"{RANKED_REPORT}: not present, skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
